"use client";

import { useState } from "react";
import { Search } from "lucide-react";
import { Header } from "@/components/layout";
import { Card } from "@/components/ui";

interface Term {
  term: string;
  definition: string;
  category: "protocol" | "blockchain" | "economy";
}

const TERMS: Term[] = [
  // Protocol
  {
    term: "ScorchCore",
    definition:
      "The burning heart of the protocol — a primordial energy source discovered deep within the Forgotten Rifts of Lunacia. It powers the entire Forge & Collect-to-Earn ecosystem.",
    category: "protocol",
  },
  {
    term: "CoreMiner",
    definition:
      "An NFT born from the Elemental Forge. CoreMiners are created by transmuting dormant Axies and passively mine $CORE tokens based on their stats and type.",
    category: "protocol",
  },
  {
    term: "Geode",
    definition:
      "A Crystalline Geode NFT created during the Forge process. It incubates before hatching into a CoreMiner with randomized stats and rarity.",
    category: "protocol",
  },
  {
    term: "Elemental Forge",
    definition:
      "The core mechanism of the protocol. Select dormant Axies, add SLP and resources, and transmute them into Crystalline Geodes that hatch into CoreMiners.",
    category: "protocol",
  },
  {
    term: "Resonance Power",
    definition:
      "A passive bonus generated by staking Axies in the protocol. Higher Resonance Power increases mining efficiency for your CoreMiners.",
    category: "protocol",
  },
  {
    term: "TrustScore",
    definition:
      "A reputation metric that tracks player behavior and engagement. Higher TrustScore unlocks better mining rates and protocol benefits.",
    category: "protocol",
  },
  {
    term: "Set Bonus",
    definition:
      "A permanent bonus earned by collecting specific combinations of CoreMiners. Complete sets grant additional mining power and unique rewards.",
    category: "protocol",
  },
  {
    term: "Memento",
    definition:
      "A consumable item used during the Forge process to guarantee success or improve the odds of hatching rare CoreMiners.",
    category: "protocol",
  },
  {
    term: "Hatching",
    definition:
      "The process of opening a Geode to reveal the CoreMiner inside. Each Geode has 7 possible CoreMiner outcomes per type, with a 1% chance of a Critical (rare) result.",
    category: "protocol",
  },
  {
    term: "Mining Cycle",
    definition:
      "A timed period during which a CoreMiner is locked and actively mining $CORE. Longer cycles yield higher rewards but lock the miner for more time.",
    category: "protocol",
  },
  {
    term: "Prospector",
    definition:
      "Any player participating in the ScorchCore Protocol — forging CoreMiners, mining $CORE, and contributing to the ecosystem.",
    category: "protocol",
  },
  // Economy
  {
    term: "$CORE",
    definition:
      "The native utility token of ScorchCore Protocol with a hard cap of 2.1 Billion tokens. Used for upgrades, repairs, governance, and staking. Follows an annual halving emission schedule.",
    category: "economy",
  },
  {
    term: "$fCORE",
    definition:
      "Fractional CORE — a non-transferable token representing unmined $CORE rewards. Must be converted to $CORE through the Proof-of-Humanity verification process.",
    category: "economy",
  },
  {
    term: "Halving",
    definition:
      "An annual event that cuts the $CORE emission rate by 50%, creating programmed scarcity similar to Bitcoin's halving mechanism.",
    category: "economy",
  },
  {
    term: "Burn-to-Earn",
    definition:
      "The core economic model: dormant Axies are burned (transmuted) to create CoreMiners, permanently reducing Axie supply while generating new productive assets.",
    category: "economy",
  },
  {
    term: "Vesting",
    definition:
      "A time-locked token release schedule. Team and treasury $CORE allocations are vested over time to ensure long-term alignment.",
    category: "economy",
  },
  {
    term: "Buyback",
    definition:
      "A protocol mechanism that uses treasury funds to purchase $CORE from the open market, supporting token price and reducing circulating supply.",
    category: "economy",
  },
  // Blockchain
  {
    term: "Ronin",
    definition:
      "An EVM-compatible blockchain built by Sky Mavis specifically for gaming. ScorchCore Protocol is deployed on Ronin for fast, low-cost transactions.",
    category: "blockchain",
  },
  {
    term: "Wallet",
    definition:
      "A digital account that holds your tokens and NFTs on the blockchain. ScorchCore uses the Ronin Waypoint wallet for seamless authentication.",
    category: "blockchain",
  },
  {
    term: "NFT (Non-Fungible Token)",
    definition:
      "A unique digital asset on the blockchain. In ScorchCore, CoreMiners and Geodes are NFTs with distinct properties and ownership.",
    category: "blockchain",
  },
  {
    term: "Smart Contract",
    definition:
      "Self-executing code on the blockchain that powers all protocol operations — forging, mining, staking, and token distribution — without intermediaries.",
    category: "blockchain",
  },
  {
    term: "Staking",
    definition:
      "Locking tokens or NFTs in a smart contract to earn rewards. In ScorchCore, staking Axies generates Resonance Power.",
    category: "blockchain",
  },
  {
    term: "Gas Fee",
    definition:
      "A small transaction fee paid to process operations on the blockchain. Ronin's low gas fees make ScorchCore accessible to all players.",
    category: "blockchain",
  },
  {
    term: "Mint",
    definition:
      "The process of creating a new token or NFT on the blockchain. When a Geode hatches, a new CoreMiner NFT is minted.",
    category: "blockchain",
  },
  {
    term: "Burn",
    definition:
      "Permanently destroying a token or NFT by sending it to an irrecoverable address. Burning is central to the Forge transmutation process.",
    category: "blockchain",
  },
];

const CATEGORY_LABELS: Record<
  Term["category"],
  { label: string; icon: string }
> = {
  protocol: { label: "Protocol", icon: "🔥" },
  economy: { label: "Economy", icon: "💰" },
  blockchain: { label: "Blockchain", icon: "⛓️" },
};

export default function TerminologyPage() {
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState<
    Term["category"] | "all"
  >("all");

  const filtered = TERMS.filter((t) => {
    const matchesSearch =
      search === "" ||
      t.term.toLowerCase().includes(search.toLowerCase()) ||
      t.definition.toLowerCase().includes(search.toLowerCase());
    const matchesCategory =
      activeCategory === "all" || t.category === activeCategory;
    return matchesSearch && matchesCategory;
  });

  return (
    <div className="min-h-screen bg-black text-white">
      <Header />

      <main className="container mx-auto px-4 py-12">
        {/* Page Header */}
        <div className="max-w-3xl mx-auto text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-linear-to-r from-orange-500 to-red-600 bg-clip-text text-transparent">
            Terminology
          </h1>
          <p className="text-gray-400 text-lg">
            A comprehensive glossary of terms used in the ScorchCore Protocol
            ecosystem.
          </p>
        </div>

        {/* Search & Filters */}
        <div className="max-w-3xl mx-auto mb-8 space-y-4">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500" />
            <input
              type="text"
              placeholder="Search terms..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-12 pr-4 py-3 bg-gray-900 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-orange-500 transition-colors"
            />
          </div>

          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              onClick={() => setActiveCategory("all")}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                activeCategory === "all"
                  ? "bg-orange-500/20 text-orange-400 border border-orange-500/50"
                  : "bg-gray-800 text-gray-400 border border-gray-700 hover:text-white"
              }`}
            >
              All ({TERMS.length})
            </button>
            {(Object.keys(CATEGORY_LABELS) as Term["category"][]).map((cat) => {
              const count = TERMS.filter((t) => t.category === cat).length;
              return (
                <button
                  key={cat}
                  type="button"
                  onClick={() => setActiveCategory(cat)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                    activeCategory === cat
                      ? "bg-orange-500/20 text-orange-400 border border-orange-500/50"
                      : "bg-gray-800 text-gray-400 border border-gray-700 hover:text-white"
                  }`}
                >
                  {CATEGORY_LABELS[cat].icon} {CATEGORY_LABELS[cat].label} (
                  {count})
                </button>
              );
            })}
          </div>
        </div>

        {/* Terms Grid */}
        <div className="max-w-3xl mx-auto space-y-4">
          {filtered.length === 0 ? (
            <div className="text-center py-12 text-gray-500">
              <p className="text-lg">No terms found matching your search.</p>
            </div>
          ) : (
            filtered.map((item) => (
              <Card key={item.term} variant="glass" className="p-6">
                <div className="flex items-start gap-4">
                  <span className="text-2xl mt-0.5">
                    {CATEGORY_LABELS[item.category].icon}
                  </span>
                  <div>
                    <h3 className="text-lg font-bold text-white mb-1">
                      {item.term}
                    </h3>
                    <span className="inline-block px-2 py-0.5 mb-2 text-xs rounded bg-gray-800 text-gray-400 border border-gray-700">
                      {CATEGORY_LABELS[item.category].label}
                    </span>
                    <p className="text-gray-400 leading-relaxed">
                      {item.definition}
                    </p>
                  </div>
                </div>
              </Card>
            ))
          )}
        </div>
      </main>
    </div>
  );
}
